### PR TITLE
Revert noarch

### PR DESCRIPTION
**Pull request by jakirkham**
Switches back to an arch-based build as `wheel` is a dependency of `pip` and is common to include in `constructor`-based installs. Mainly because `pip` gets pulled in by `python` by default.

Edit: For history, this was originally made `noarch: python` in PR ( https://github.com/conda-forge/wheel-feedstock/pull/5 ).

~~Edit 2: Think that `noarch: python` was causing issue ( https://github.com/conda-forge/wheel-feedstock/issues/8 ) as well.~~ Turns out that issue was unrelated.

### CODE REVIEW

**Comment by jakirkham** [comment]
Just ran into this issue recently and am finding the need to turn this back an arch specific package.

cc-ing @sannykr @mariusvniekerk

**Comment by jakirkham** [comment]
Merging tomorrow if no comments.

**Comment by minrk** [comment]
@jakirkham we were using frozen environments via `conda export` on binder, which happened to pull this build in. This caused conda installs to fail because we had frozen the py_0 version, which `conda install` no longer fetches due to being marked `broken`. If the noarch wheel isn't in fact broken, can it be restored so that these envs aren't broken anymore?

**Comment by jakirkham** [comment]
So it was my error to allow `noarch: python` here in the first place. The reason being we have tried very hard to ensure that `conda` and dependencies are not `noarch`. This is important for upgrading older `conda` installs before the `noarch` additions. I could temporarily remove the `broken` label, but we really should be marking it as `broken`. Sorry for the trouble it has caused.

**Comment by minrk** [comment]
That's fine, I just misinterpreted the comment that it's not really broken. Thanks!

**Comment by jakirkham** [comment]
The package itself works. It's the fact that it is so low level in the stack and was being made `noarch` that made it problematic.

If putting it in `main` will save some near term pain, happy to do it. We just should move it back to `broken` once the environments are updated.

**Pull request merged**
